[package]
name = "knocknoc"
version = "0.1.13"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Data structure serialization library with several opposite design goals from Serde."
repository = "https://github.com/dtolnay/knocknoc"
documentation = "https://docs.rs/knocknoc"
readme = "README.md"
edition = "2018"

[dependencies]
itoa = "0.4.3"
knocknoc_internal = { version = "=0.1.13", path = "derive" }
ryu = "1.0"
base64 = "0.12"

[dev-dependencies]
automod = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[workspace]
members = ["derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
